[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "no-store"
