headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"
pinned_version = "5"

[plugins.inputs]

[build]
publish = "C:\\Users\\ajsga\\Desktop\\Maia Web-Sites Folder\\lleva-lleva\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]